### ISSUE TITLE
Audio files for faculty name pronunciations

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/faculty-directory#86]
Desire is to have faculty name audio snippet show up on SiteFarm for subset of faculty who want it.

Possible implementation:

1. Create a Link where faculty (or admin) could log in and create/update their audio file using [some react library](https://www.npmjs.com/package/mic-recorder-to-mp3)
2. On save, we push file directly to SiteFarm via API (maybe similar to how we do profile pictures??) and store the audio file UUID in our db
3. When creating/updating the "bio" HTML for a person, if there is an auto file we add a <drupal-media> tag like so: 
`<drupal-media data-align="" data-entity-type="media" data-entity-uuid="21b55c20-5692-40ff-96a8-493f97e8e39f"></drupal-media>`

**Comment by sprucely** [comment]
I'm not familiar enough with the faculty app. So there is already a database, or is SiteFarm the database? Seems like a decent approach to me. Since the clip would be accessed within SiteFarm, I suppose we wouldn't have to deal with the CORS proxy stuff.

**Comment by srkirkland** [comment]
Some info about saving files directly to sitefarm https://codepen.io/collection/RzgQJy

**Comment by srkirkland** [comment]
Also https://v1.nameshouts.com/developer as an option.  affordable.  But it would have to work for a large % of our faculty for it to be a good solution

**Comment by srkirkland** [comment]
fixed in #92
